### ISSUE TITLE
Tool testing

### ISSUE THREAD

**Issue by Pyreaus** [AzizKpln/Social_X#1]
Hello, I've tested your tool and the concept is very good, except I can't get past the input screen after entering the files the script doesn't load anything for a few minutes then returns the following output: 

**[-]Please Choose Another Name.This Name IS Already IN The Server Cwby1.jpeg**

Please look into this :-)

**Comment by AzizKpln** [comment]
Hi,

You're getting that error because my servers are currently not active.

**Comment by Pyreaus** [comment]
> 
> 
> Hi,
> 
> You're getting that error because my servers are currently not active.

Are you relisting the servers?

**Comment by AzizKpln** [comment]
yes but my fud backdoor algorithm is now detectable. Im not gonna put in much effort on it because it won't stay fully undetectable for long. Im replacing the backdoor with a reverse shell and im not running the servers on a vps anymrore. In new version of this tool, servers will be on a local server. User will be able to open the server for public with a reverse proxy software.

**Comment by Pyreaus** [comment]
ok, understood. So local server will have the listener for persistence?

**Comment by AzizKpln** [comment]
yes

**Comment by AzizKpln** [comment]
New version is released You can try it now. Let me know incase of having any kind of issue.

**Comment by Pyreaus** [comment]
Ok I will, thank your for the notification
